### ISSUE TITLE
Html files don't copy on change

### ISSUE THREAD

**Issue by nickolasacosta** [revuniversal/just-react#5]
in your package.json, the "copy" script doesn't run on change like the webpack watcher does.  Any changes made to the html in the "src" folder will not be copied over on save. 

lite-server doesn't auto refresh as a result.

fix when?

**Comment by revuniversal** [comment]
Long wait for a reply, but...
I think there are some issues to explore with this.  I'm not sure that the live-reload can reload the host page without causing some unwanted loss of state.  I wouldn't turn down a pull-request if you think there's a solution.
